# Generated by Django 2.0.3 on 2018-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DartsRecognitionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField()),
                ('since', models.DateTimeField(verbose_name='date started')),
            ],
        ),
    ]
