# Generated by Django 2.0.3 on 2018-03-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartDartsRecognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_date', models.DateTimeField(verbose_name='date updated')),
                ('is_automated_darts_recognition_started', models.BooleanField()),
            ],
        ),
    ]
